//try catch Block

let name ;
try{


    HRISHI
}
catch(err)
{
    console.log(err.message)
    console.log(err.name);
}